### PR TITLE
Gb/disable

### LINKED ISSUE #557: Allow users to deactivate a genome build
- [x] Add button to the GB ViewEntry (VE) to deactivate the genome build (like done on other VEs)

- [x] Show form to deactive GB (`/genome_builds/hg19?remove`)
  - [x] Just give a warning and require a password, no other fields needed.

- [x] Give an error and block removal when:
   - [x] The chosen ID is not among the active IDs
   - [x] Password is incorrect
   - [x] There are variants on the chosen genome build that are not yet mapped on one of the other active genome builds

- [x] Delete entry if all variants are safely mapped on another genome build
   - [x] Delete row from Genome build table
   - [x] Alter VOG table (deleting the start, end, and DNA columns)
   - [x] Deactivate the custom DNA column
   - [x] Alter Transcripts table (deleting the start and end columns)

Related to #550

### PR DESCRIPTION
**Pull request by loeswerkman**
Allows users to deactivate a given genome build.
- Adds option to deactivate in VE of genome builds, ONLY if there is more than one genome build active.
- Checks to make sure all variants are safely stored on remaining genome builds, and cancels the removal when this is not the case.

Closes #557 
Related to #550

### CODE REVIEW

File: src/genome_builds.php [hunk 1]
```diff
@@ -244,7 +244,193 @@
...
+
+        if (empty($_POST['password'])) {
+            lovd_errorAdd('password', 'Please fill in the \'Enter your password for authorization\' field.');
+
+        } elseif (!lovd_verifyPassword($_POST['password'], $_AUTH['password'])) {
+            lovd_errorAdd('password', 'Please enter your correct password for authorization.');
+
+        } else {
+            $bValidPassword = true;
+        }
```
Comment (ifokkema) [inline src/genome_builds.php]: Better stick to the LOVD defaults here;
- `lovd_errorClean()` cleans up any previous errors if there are any (almost never the case, but still).
- `lovd_errorAdd()` adds an error.
- `lovd_error()` then returns whether or not there are errors.
This way, you won't have to make your own variables.

File: src/genome_builds.php [hunk 2]
```diff
@@ -244,7 +244,193 @@
...
+            exit;
+        }
+    }
+
+
+
+    $_T->printHeader();
+    $_T->printTitle();
+
+    $sName = $sID . ' / ' . $_SETT['human_builds'][$sID]['ncbi_name'];
```
Comment (ifokkema) [inline src/genome_builds.php:400]: Better take this out of the database instead of redefining how we name a genome build. If we'd ever change how we name them, we'd need to change this code as well, or it'll mention a name that may not be used in the database.
(I'll fix this in a new commit)

File: src/genome_builds.php [hunk 3]
```diff
@@ -244,7 +244,193 @@
...
+
+    lovd_showInfoTable('This will deactivate genome build ' . $sName . ' from your database.', 'warning');
+
+    lovd_errorPrint();
+
+    // Tooltip JS code.
+    lovd_includeJS('inc-js-tooltip.php');
```
Comment (ifokkema) [inline src/genome_builds.php]: This is not wrong, but simply unneeded since this form doesn't have any tooltips. So I chose to remove it to prevent a file from getting included that wasn't used at all.

File: src/genome_builds.php [hunk 4]
```diff
@@ -384,8 +384,9 @@
             }
 
             // Deactivate custom DNA column.
+            // TODO: Colsuffix / dependant
             $_DB->query('DELETE FROM ' . TABLE_ACTIVE_COLS .
-                ' WHERE colid = "VariantOnGenome/DNA/' . $sID . '"');
+                ' WHERE colid = "VariantOnGenome/DNA' . $sSlash . $aActiveBuilds[$sID] . '"');
```
Comment (ifokkema) [inline src/genome_builds.php]: Better use PDO placeholders here (`?`). I'll fix this.

**Review by ifokkema — CHANGES_REQUESTED** [review]
Some changes required; I'll commit them separately.
